use company;
select country_name from countries ;
select email,phone_number from employees;
select * from dependents where last_name='fay';
select hire_date from employees where last_name='grant' or last_name='whalen';
select first_name,last_name from employees  where job_id=(select job_id from jobs where job_title="shipping clerk");
select * from employees where department_id=8;
select * from dept order by department_id DESC;
select * from employees where last_name like 'K%';
select first_name,last_name,hire_date from employees where hire_date between '1995-01-01' and '1997-12-31' order by hire_date asc;
select job_title from jobs where max_salary<5000;
select first_name,last_name,hire_date from employees where hire_date like '1995%';insert into employees(employee_id,first_name,last_name,email,phone_number,hire_date,job_id,salary,manager_id,department_id) values (207,'paul','newton','paulnewton@sqltutorial.org','515.123.4588','1998-06-17',15,25000,NULL,11);
select * from employees;
select email from employees;
SET SQL_SAFE_UPDATES=0;
SET FOREIGN_KEY_CHECKS=0;
delete from dept where department_name='shipping';
SET SQL_SAFE_UPDATES=1;
SET FOREIGN_KEY_CHECKS=1;
select * from dept;
